Read and decode pdu message from incoming socket
Kinetic/kinetic-js pull request #14
Opened 2017-02-14 15:57 UTC by lamphamsy

Please!

2017-02-15 10:45 UTC, koolfunky requested changes

2017-02-15 10:45 UTC, AntoninCoulibaly commented on lib/kinetic.js
> +function getPduError(pdu) {
I don't understand this function you can use : 
https://github.com/lamphamsy/kinetic-js/blob/9aa693330ce08efe032cfd511afdbb3a0bfa3d16/lib/kinetic.js#L440
and
https://github.com/lamphamsy/kinetic-js/blob/9aa693330ce08efe032cfd511afdbb3a0bfa3d16/lib/kinetic.js#L146

you can modify them if it's needed

2017-02-16 11:19 UTC, lamphamsy commented
@AntoninCoulibaly : the code is updated

2017-02-16 13:49 UTC, koolfunky approved these changes

2017-02-16 13:50 UTC, merged